### ISSUE TITLE
Method not found 

### ISSUE THREAD

**Issue by jszatanek** [ProH4Ck/treadmill-bridge#1]
Hi !
Running this app on a Windows 10 laptop, I'm facing the followin issue:
[10:35:04 DBG] Hosting starting
[10:35:04 DBG] Failed to locate the development https certificate at 'null'.
[10:35:05 DBG] Unable to locate an appropriate development https certificate.
[10:35:05 DBG] No listening endpoints were configured. Binding to http://localhost:5000 by default.
[10:35:05 INF] Now listening on: http://localhost:5000
[10:35:05 DBG] Loaded hosting startup assembly TreadmillBridge
[10:35:05 FTL] An unhandled exception occurred.
System.MissingMethodException: Method not found: 'Void Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProv
iderAdvertisingParameters.put_ServiceData(Windows.Storage.Streams.IBuffer)'.
   at TreadmillBridge.Services.VirtualTreadmill.VirtualTreadmillService.StartAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TreadmillBridge.Services.VirtualTreadmill.VirtualTreadmillService.StartAsync(CancellationToken cancellationToken)
   at TreadmillBridge.BackgroundServices.TreadmillServerBackgroundService.ExecuteAsync(CancellationToken stoppingToken)
in C:\jsz\perso\treadmill-bridge-master\src\TreadmillBridge\BackgroundServices\TreadmillServerBackgroundService.cs:line
18
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at TreadmillBridge.Program.Main(String[] args) in C:\jsz\perso\treadmill-bridge-master\src\TreadmillBridge\Program.cs
:line 19

Any Idea ? Thank you for the great work !

**Comment by ProH4Ck** [comment]
Hi,
which version of Windows 10 are you using? 
I think you are on an old unsupported version by `Microsoft.Windows.SDK.Contracts` version 10.0.18362.2005

**Comment by jszatanek** [comment]
I'm running Windows 10 Enterprise version 1809, OS Build 17763.1217, and I use Nuget in Visual Studio to link Microsoft.Windows.SDK.Contracts v 10.0.19041.1

**Comment by ProH4Ck** [comment]
You need at least 1903. I tried targeting an older version of `Microsoft.Windows.SDK.Contracts` but some APIs are missing and a rework is needed...

I'll update the readme to add this information.

**Comment by jszatanek** [comment]
isn't it possible to just add the missing windows.device.bluetooth.dll file somewhere ?

**Comment by ApieDePapie** [comment]
was this ever fixed? if so i would like to know how you did it i am currently having the same problem. :)

**Comment by cagnulein** [comment]
i'm studying to porting this great project on a raspberry
https://github.com/dotnet/runtime/issues/22597

I will try to use this library on Linux https://github.com/hashtagchris/DotNet-BlueZ

you can find my progress here https://github.com/cagnulein/treadmill-bridge

**Comment by cagnulein** [comment]
mmm after some hours spent reading the code, i think it should be easier porting it to python.

**Comment by cagnulein** [comment]
by the way, in the end i choose Qt :)

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift
